version: '3.7'

services:
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
    ports:
      - '27017:27017'
    volumes:
      - C:/docker_databases/mongodb:/etc/mongo

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME:
      ME_CONFIG_MONGODB_ADMINPASSWORD:

  rabbitmq:
    image: rabbitmq:management
    ports:
      - '5672:5672'
      - '15672:15672'

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: db_api_spring_rest
      MYSQL_ROOT_USE: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - C:/docker_databases/mysql:/var/lib/mysql
