version: '3.7'

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: db_api_spring_rest
      MYSQL_ROOT_USE: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - C:/docker_databases/mysql:/var/lib/mysql

    # command:
    #   - revoke all on db_api_spring_rest.* from 'root'@'%';
    #   - grant select, insert, delete, update on db_api_spring_rest.* to 'root'@'%';
  rabbitmq:
    image: rabbitmq:management
    ports:
      - '5672:5672'
      - '15672:15672'
